version: '2'
services:
  php_fpm56:
    build: ./
    restart: on-failure
    volumes:
      - ./fpm56/fpm/pool.d/www.conf:/etc/php/5.6/fpm/pool.d/www.conf:rw
      - /home/user/webapp/scatter-slots/:/home/user/webapp/
    ports:
      - "9011:9000"
    networks:
      - app_network
networks:
  app_network:
    external:
      name: app_network
