version: '2'
services:
    # php:
    #     build: ./php
    #     volumes:
    #         - ../ncs:/code
    #         - $HOME/.ssh:/root/.ssh
    php:
        build: ./fpm56
        restart: on-failure
        volumes:
          - ./fpm56/fpm/pool.d/www.conf:/etc/php/5.6/fpm/pool.d/www.conf:rw
          - ../ncs:/code
          - $HOME/.ssh:/root/.ssh
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ../ncs:/code
            - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php


  # web:
  #   build: ./web
  #   ports:
  #     - "8080:80"
  #   environment:
  #       XDEBUG_CONFIG: remote_host=192.168.0.102
  #       PHP_IDE_CONFIG: "serverName=project"
  #   volumes:
  #     - ../ncs:/code

    # depends_on:
    #   - db
    #   - redis
    #   - rabbitmq
